#!/usr/bin/env node
/**
 * council-env.mjs — 会議ハーネスに必要な env の診断と流し込み（2026-08-25 新設）
 *
 * なぜ在るか:
 *  必要な env の一覧が「コード・COUNCIL-HOWTO・council-fableスキル」の3箇所に
 *  手書きコピーされ、SambaNova(07-31)とMistral(08-05)の追加時に文書側2箇所とも
 *  漏れた。その結果スキル経由の会議が半月以上 16体中12体で回っていた
 *  （critic 4→2・lead 3→2・implement 2→1）。meeting.mjs が該当メンバーを
 *  無言で skip するため誰も気づけなかった。
 *  → 一覧は council-lineup.mjs の ENV_NAMES ただ1つを正本とし、
 *    文書からは一覧を消してこのコマンドを案内する。
 *
 * 使い方:
 *   node scripts/council-env.mjs
 *     どの env が有効／欠落か、欠落すると誰が落ちるかを表示する（日本語）。
 *
 *   node scripts/council-env.mjs --ps
 *     User scope の環境変数をプロセスに流す PowerShell 断片を出力する。
 *     PowerShell 側ではこう使う:
 *       Invoke-Expression (node scripts/council-env.mjs --ps | Out-String)
 *     ★出力は ASCII のみ（この環境では PowerShell に日本語を渡すと化けるため。
 *       日本語の説明は既定モードだけに置く）。
 *
 * 何もしない: キーの値は表示しない（長さと有無だけ）。取得も設定もしない。
 */
import { LINEUP, ENV_NAMES } from './council-lineup.mjs';
import { roleOf } from './council-roles.mjs';

const psMode = process.argv.includes('--ps');

// 略号 -> その略号を必要とするメンバー一覧
const byFlag = {};
for (const entry of LINEUP) {
  for (const k of entry.requires || []) (byFlag[k] = byFlag[k] || []).push(entry);
}

if (psMode) {
  // ASCII only. 1行1変数で、User scope に値があるものだけを流す。
  const names = Object.values(ENV_NAMES);
  console.log('# generated by scripts/council-env.mjs --ps (do not hand-edit the list)');
  console.log(`foreach ($n in @(${names.map((n) => `'${n}'`).join(',')})) {`);
  console.log('  $v = [Environment]::GetEnvironmentVariable($n, \'User\')');
  console.log('  if ($v) { Set-Item -Path "Env:$n" -Value $v }');
  console.log('}');
  process.exit(0);
}

let enabled = 0;
const lackedBy = {};
for (const entry of LINEUP) {
  const lack = (entry.requires || []).filter((k) => !process.env[ENV_NAMES[k]]);
  if (!lack.length) { enabled++; continue; }
  for (const k of lack) (lackedBy[ENV_NAMES[k]] = lackedBy[ENV_NAMES[k]] || []).push(entry);
}

console.log(`会議メンバー: 有効 ${enabled}/${LINEUP.length}体`);
console.log('');
console.log('env の状態:');
for (const [flag, name] of Object.entries(ENV_NAMES)) {
  const v = process.env[name];
  const users = (byFlag[flag] || []).length;
  console.log(`  ${v ? '✓' : '✗'} ${name.padEnd(24)} ${users}体が使用${v ? '' : '  ← 未設定'}`);
}

if (Object.keys(lackedBy).length) {
  console.log('');
  console.log('欠落により落ちるメンバー:');
  for (const [name, members] of Object.entries(lackedBy)) {
    console.log(`  ${name}:`);
    for (const m of members) console.log(`    - ${m.label} (${roleOf(m.label) || '(none)'})`);
  }
  console.log('');
  console.log('PowerShell で流し込む:');
  console.log('  Invoke-Expression (node scripts/council-env.mjs --ps | Out-String)');
} else {
  console.log('');
  console.log('欠落なし。全メンバーが会議に出られる。');
}
